In [1]:
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import os
from pathlib import Path

In [2]:
data = pd.read_csv("data/EDA_data.csv")
data.head(5)

   free_bikes  bike_station  empty_slots  latitude  longitude  rating
0           6             0           41  41.96909 -87.674237     3.5
1           6             0           41  41.96909 -87.674237     0.0
2           6             0           41  41.96909 -87.674237     4.5
3           6             0           41  41.96909 -87.674237     4.0
4           6             0           41  41.96909 -87.674237     5.0

In [3]:
data.describe()

,free_bikes,bike_station,empty_slots,latitude,longitude,rating
count,533.000000,533.000000,533.000000,533.000000,533.000000,533.000000
mean,6.328330,51.928705,11.210131,41.891779,-87.657089,2.845216
std,6.013072,29.024532,8.949153,0.064563,0.037219,1.620174
min,0.000000,0.000000,0.000000,41.758670,-87.774704,0.000000
25%,2.000000,27.000000,6.000000,41.853534,-87.674237,2.000000
50%,5.000000,53.000000,9.000000,41.884616,-87.653449,3.500000
75%,10.000000,77.000000,14.000000,41.928887,-87.630890,4.000000
max,36.000000,100.000000,41.000000,42.048214,-87.585340,5.000000

In [4]:
y = data['free_bikes']
indep = data.drop('free_bikes', axis=1)

# X=[]
# for column in indep.columns:
#     X.append(sm.add_constant(indep[column]))

#Create a model for each indep. variable
#list of X's (with constants)
X = [sm.add_constant(indep[column]) for column in indep.columns] 
X

[     const  bike_station
 0      1.0             0
 1      1.0             0
 2      1.0             0
 3      1.0             0
 4      1.0             0
 ..     ...           ...
 528    1.0           100
 529    1.0           100
 530    1.0           100
 531    1.0           100
 532    1.0           100

 [533 rows x 2 columns],
      const  empty_slots
 0      1.0           41
 1      1.0           41
 2      1.0           41
 3      1.0           41
 4      1.0           41
 ..     ...          ...
 528    1.0            2
 529    1.0            2
 530    1.0            2
 531    1.0            2
 532    1.0            2

 [533 rows x 2 columns],
      const   latitude
 0      1.0  41.969090
 1      1.0  41.969090
 2      1.0  41.969090
 3      1.0  41.969090
 4      1.0  41.969090
 ..     ...        ...
 528    1.0  41.803023
 529    1.0  41.803023
 530    1.0  41.803023
 531    1.0  41.803023
 532    1.0  41.803023

 [533 rows x 2 columns],
      const  longitude
 0      1.0 -87.674237
 1      1.0 -87.674237
 2      1.0 -87.674237
 3      1.0 -87.674237
 4      1.0 -87.674237
 ..     ...        ...
 528    1.0 -87.664699
 529    1.0 -87.664699
 530    1.0 -87.664699
 531    1.0 -87.664699
 532    1.0 -87.664699

 [533 rows x 2 columns],
      const  rating
 0      1.0     3.5
 1      1.0     0.0
 2      1.0     4.5
 3      1.0     4.0
 4      1.0     5.0
 ..     ...     ...
 528    1.0     0.0
 529    1.0     3.5
 530    1.0     4.0
 531    1.0     5.0
 532    1.0     1.0

 [533 rows x 2 columns]]

In [5]:
Models = [sm.OLS(y,x) for x in X] #list of models
Results = [model.fit() for model in Models] #list of results
Adj_Rsquared = [results.rsquared_adj for results in Results] #list of rsquared
Pval = [results.pvalues for results in Results] #list of p-values
Params = [results.params for results in Results] #list of params

In [6]:
for i in range(len(Adj_Rsquared)):
     print(f'adj_R2: {Adj_Rsquared[i]:.3f}, P-values: {*Pval[i],}, column: {indep.columns[i]}')

adj_R2: 0.002, P-values: (3.4384962766100696e-34, 0.15404158246940072), column: bike_station
adj_R2: 0.068, P-values: (9.408105972450848e-70, 6.775946997797088e-10), column: empty_slots
adj_R2: -0.001, P-values: (0.526318938801532, 0.5509848992723128), column: latitude
adj_R2: 0.024, P-values: (0.0001771887701884925, 0.00018455230217704873), column: longitude
adj_R2: -0.002, P-values: (3.2780023414544914e-28, 0.7086219138435512), column: rating

In [7]:
#run full model
y = data['free_bikes']
X = data.drop('free_bikes', axis=1)
X = sm.add_constant(X) #adds a column of 1's so the model will contain an intercept

model = sm.OLS(y, X)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             free_bikes   R-squared:                       0.152
Model:                            OLS   Adj. R-squared:                  0.144
Method:                 Least Squares   F-statistic:                     18.83
Date:                Thu, 27 Apr 2023   Prob (F-statistic):           3.03e-17
Time:                        12:50:30   Log-Likelihood:                -1668.1
No. Observations:                 533   AIC:                             3348.
Df Residuals:                     527   BIC:                             3374.
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         4197.7296    609.850      6.883      0.000    2999.695    5395.764
bike_station    -0.0130      0.009     -1.483      0.139      -0.030       0.004
empty_slots     -0.2492      0.029     -8.535      0.000      -0.307      -0.192
latitude        10.3208      4.347      2.374      0.018       1.782      18.860
longitude       52.7114      7.527      7.003      0.000      37.924      67.499
rating           0.0840      0.150      0.560      0.575      -0.211       0.379
==============================================================================
Omnibus:                      306.719   Durbin-Watson:                   0.352
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2443.698
Skew:                           2.458   Prob(JB):                         0.00
Kurtosis:                      12.266   Cond. No.                     2.83e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.83e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [8]:
RESULTS: the model is not good fit because R-square is too low

SyntaxError: invalid syntax (699502899.py, line 1)